name: Java CI with Maven

# Trigger the workflow when pushing to the 'main' branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    # The runner will use the latest version of Ubuntu
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Java (JDK 11 in this case)
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    # Step 3: Cache Maven dependencies to speed up build
    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Step 4: Build the Java project using Maven
    - name: Build with Maven
      run: mvn clean install

    # Step 5: Run tests
    - name: Run tests with Maven
      run: mvn test

    # Step 6: Deploy (This is a placeholder step, replace with actual deployment logic)
    - name: Deploy application
      run: |
        echo "Deploying the Java application..."
        # Add your deployment logic here, e.g., deploying to a server or cloud.
